export interface News {
    id: string,
    createdDate: string,
    modifiedDate: string,
    createdUser: string,
    modifiedUser: string,
    isDeleted: boolean,
    categoryId: string,
    categoryName: string,
    categoryCode: string,
    title: string,
    content: string,
    imageId: string,
    attachmentId: string,
    resourceCode: string,
    resourceName: string,
    resourceUrl: string,
    postDate: string,
    status: string,
    level: string,
    posterId: string,
    posterName: string,
    approverId: string,
    approverName: string,
    countViews: string,
    newsTagDtos: string[],
    newsMetaKeywordDtos: string[],
    shortDescription: string,
    slug: string,
}
export type RequestGetNews = {
    tagName: string,
    filter: string,
    categoryId: string,
    categoryCode: string,
    categoryName: string,
    title: string,
    keyword: string,
    type: string,
    status: string,
    level: string,
    createdDate: {
      fromValue: string,
      toValue: string,
    },
    page:number,
    size: number,
}